name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: riok/kreyac:latest
    defaults:
      run:
        working-directory: example-project
    steps:
      - uses: actions/checkout@v3
      - run: kreyac info
      - run: kreyac environment list
      - run: kreyac environment set-active production
      - run: kreyac operation invoke "REST/wttr.in/London.krop" # invoke a single REST operation
      - run: kreyac operation invoke "gRPC/Unary call.krop" # invoke a single gRPC operation
      - run: kreyac operation invoke "Kreya features/Scripting/**" # invoke all scripting operations